root: true
env:
  browser: true
  jest: true
extends:
  [
    "standard-with-typescript",
    "next/core-web-vitals",
    "plugin:prettier/recommended",
  ]
parser: "@typescript-eslint/parser"
parserOptions:
  project: ["tsconfig.json", "src", "test"]
ignorePatterns: ["dist", "build", "node_modules"]
